just added some useful features
iammrhelo/InstagramCrawler pull request #11
Opened 2017-07-22 12:08 UTC by leabdalla

2017-07-23 13:01 UTC, JakeCowton requested changes
I've suggested a change to how the headless parameter is passed around the code. It means you don't need to put `-l 1` in the command line and can just use `-l`.

(I made a PR for this on your branch)

2017-07-23 13:01 UTC, JakeCowton commented on instagramcrawler.py
> +    parser.add_argument('-l', '--headless', type=int, default=0,
I'd recommend storing this in the same way the captions are stored using `action='store_true'`, that way you can just pass `-l` without having to supply `1`
```
parser.add_argument('-l', '--headless', action='store_true',
                                   help='If set, will use PhantomJS driver to run script as headless')
```

2017-07-23 13:01 UTC, JakeCowton commented on instagramcrawler.py
> +    def __init__(self, headless=0):
Change this to
`def __init__(self, headless=False`

2017-07-23 13:01 UTC, JakeCowton commented on instagramcrawler.py
> +        if(headless == 1):
Change this to `if headless:`

2017-07-24 02:45 UTC, iammrhelo commented
@JakeCowton @leabdalla 
Thanks!
I'll look at it later

2017-07-25 11:59 UTC, iammrhelo commented
I'll merge it after adding some tests...

2017-07-27 06:15 UTC, merged

2017-07-27 06:20 UTC, iammrhelo commented
@leabdalla 
merged